AWSTemplateFormatVersion:               "2010-09-09"
Description:                            "Daily aggregation of CloudTrail events into NDJSON"

Parameters:

  LambdaName:
    Description:                        "Name for the Lambda function and associated resources"
    Type:                               "String"
    Default:                            "cloudtrail-aggregation-daily"

  MaximumConcurrency:
    Description:                        "The number of concurrent Lambda executions; increase to handle a backlog (minimum is 2)"
    Type:                               "Number"
    Default:                            8

  SrcBucket:
    Description:                        "Name of the bucket holding raw CloudTrail logs"
    Type:                               "String"

  SrcPrefix:
    Description:                        "Prefix for raw CloudTrail logs (typically this is AWSLogs/ORG/, where ORG is the organization ID; must include trailing slash)"
    Type:                               "String"

  DstBucket:
    Description:                        "Name of the bucket to receive aggregated logs (will be created)"
    Type:                               "String"

  DstPrefix:
    Description:                        "Prefix for aggregated CloudTrail logs in the destination bucket (must include trailing slash)"
    Type:                               "String"
    Default:                            "cloudtrail-daily/"


Resources:

  LambdaLogGroup:
    Type:                               "AWS::Logs::LogGroup"
    DeletionPolicy:                     "Delete"
    Properties:
      LogGroupName:                     !Sub "/aws/lambda/${LambdaName}"
      RetentionInDays:                  7


  LambdaRole:
    Type:                               "AWS::IAM::Role"
    Properties:
      Path:                             "/lambda/"
      RoleName:                         !Sub "${LambdaName}-ExecutionRole-${AWS::Region}"
      AssumeRolePolicyDocument:
        Version:                        "2012-10-17"
        Statement:
          Effect:                       "Allow"
          Principal:
            Service:                    "lambda.amazonaws.com"
          Action:                       "sts:AssumeRole"
      ManagedPolicyArns:
        -                               "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Policies:
        - PolicyName:                   "OperationalPolicy"
          PolicyDocument:
            Version:                    "2012-10-17"
            Statement:
              - Sid:                      "ListSource"
                Effect:                   "Allow"
                Action:                   
                  -                       "s3:ListBucket"
                Resource:                 
                  -                       !Sub "arn:${AWS::Partition}:s3:::${SrcBucket}"
              - Sid:                      "ReadSource"
                Effect:                   "Allow"
                Action:                   
                  -                       "s3:GetObject"
                Resource:                 
                  -                       !Sub "arn:${AWS::Partition}:s3:::${SrcBucket}/${SrcPrefix}*"
              - Sid:                      "WriteDestination"
                Effect:                   "Allow"
                Action:                   
                  -                       "s3:PutObject"
                Resource:                 
                  -                       !Sub "arn:${AWS::Partition}:s3:::${DstBucket}/${DstPrefix}*"
              - Sid:                      "SQS"
                Effect:                   "Allow"
                Action:                   
                  -                       "sqs:ReceiveMessage"
                  -                       "sqs:DeleteMessage"
                  -                       "sqs:GetQueueAttributes"
                Resource:                 
                  -                       !GetAtt TriggerQueue.Arn


  LambdaFunction:
    Type:                               "AWS::Lambda::Function"
    Properties:
      FunctionName:                     !Ref LambdaName
      Description:                      "Stage 1 CloudTrail aggregation: combines a day's raw logfiles into a single compressed NDJSON file"
      Role:                             !GetAtt LambdaRole.Arn
      Runtime:                          "python3.11"
      Handler:                          "index.lambda_handler"
      Code:
        ZipFile:                        |
                                        def lambda_handler(event, context):
                                            print("this is a dummy handler; replace with contents of lambda.py")
      MemorySize:                       512
      Timeout:                          900
      Environment:
        Variables:
          LOG_LEVEL:                    "INFO"
          SRC_BUCKET:                   !Ref SrcBucket
          SRC_PREFIX:                   !Ref SrcPrefix
          DST_BUCKET:                   !Ref DstBucket
          DST_PREFIX:                   !Ref DstPrefix


  TriggerQueue:
    Type:                               "AWS::SQS::Queue"
    Properties: 
      QueueName:                        !Sub "${LambdaName}-trigger"
      MessageRetentionPeriod:           1209600
      VisibilityTimeout:                1200  # 20 minutes; will redrive if Lambda times out
      RedrivePolicy: 
        deadLetterTargetArn:            !GetAtt TriggerDLQ.Arn
        maxReceiveCount:                1


  TriggerDLQ:
    Type:                               "AWS::SQS::Queue"
    Properties: 
      QueueName:                        !Sub "${LambdaName}-dlq"
      MessageRetentionPeriod:           1209600


  Trigger:
    Type:                               "AWS::Lambda::EventSourceMapping"
    Properties:
      BatchSize:                        1
      EventSourceArn:                   !GetAtt TriggerQueue.Arn
      FunctionName:                     !GetAtt LambdaFunction.Arn
      ScalingConfig: 
        MaximumConcurrency:             !Ref MaximumConcurrency 


  Schedule:
    Type:                               "AWS::Scheduler::Schedule"
    Properties:
      Name:                             !Ref LambdaName
      Description:                      !Sub "Triggers the CloudTrail aggregation Lambda managed by stack ${AWS::StackName}"
      ScheduleExpression:               "cron(0 1 * * ? *)"
      ScheduleExpressionTimezone:       "UTC"
      FlexibleTimeWindow:
        Mode:                           "OFF"
      State:                            "ENABLED"
      Target: 
        Arn:                            !GetAtt TriggerQueue.Arn
        RoleArn:                        !GetAtt ScheduleRole.Arn


  ScheduleRole:
    Type:                               "AWS::IAM::Role"
    Properties:
      RoleName:                         !Sub "${LambdaName}-EventBridgeRole-${AWS::Region}"
      AssumeRolePolicyDocument:
        Version:                        "2012-10-17"
        Statement:
          Effect:                       "Allow"
          Principal:
            Service:                    "scheduler.amazonaws.com"
          Action:                       "sts:AssumeRole"
          Condition:
            StringEquals:               { "aws:SourceAccount": !Ref AWS::AccountId }
      Policies:
        - PolicyName:                   "OperationalPolicy"
          PolicyDocument:
            Version:                    "2012-10-17"
            Statement:
              - Sid:                      "SendMessage"
                Effect:                   "Allow"
                Action:                   
                  -                       "sqs:SendMessage"
                Resource:                 
                  -                       !GetAtt TriggerQueue.Arn


Outputs:

  TriggerQueueUrl:
    Description:                        "URL of the queue that triggers Lambda"
    Value:                              !Ref TriggerQueue
