AWSTemplateFormatVersion:               "2010-09-09"
Description:                            "An example of S3 file handling using Lambdas"

Parameters:

  BaseBucketName:
    Description:                        "A prefix used for all S3 buckets created by this stack"
    Type:                               "String"
    Default:                            ""


Resources:

  ##
  ## Buckets
  ##

  StaticBucket:
    Type:                               "AWS::S3::Bucket"
    Properties: 
      BucketName:                       !Sub "${BaseBucketName}-static"
      AccessControl:                    "PublicRead"


  UploadBucket:
    Type:                               "AWS::S3::Bucket"
    DependsOn:                          [ ProcessorInvocationPermission ]
    Properties: 
      BucketName:                       !Sub "${BaseBucketName}-uploads"
      AccessControl:                    "Private"
      CorsConfiguration:
        CorsRules:
          -
            AllowedMethods:             ["PUT"]
            AllowedOrigins:             [ "*" ]
            AllowedHeaders:             [ "*" ]
      LifecycleConfiguration: 
        Rules:
          -
            Id:                         "DeleteUnprocessedUploads"
            ExpirationInDays:           1
            Status:                     "Enabled"
      NotificationConfiguration:
        LambdaConfigurations:
          -
            Event:                      "s3:ObjectCreated:*"
            Function:                   !GetAtt ProcessorFunction.Arn


  ArchiveBucket:
    Type:                               "AWS::S3::Bucket"
    Properties: 
      BucketName:                       !Sub "${BaseBucketName}-archive"
      AccessControl:                    "Private"


  ##
  ## File-Processing Lambda
  ##

  ProcessorLogGroup:
    Type:                               "AWS::Logs::LogGroup"
    DeletionPolicy:                     "Delete"
    Properties:
      LogGroupName:                     !Sub "/aws/lambda/${AWS::StackName}-Processor"
      RetentionInDays:                  7


  ProcessorRole:
    Type:                               "AWS::IAM::Role"
    Properties:
      Path:                             "/lambda/"
      RoleName:                         !Sub "${AWS::StackName}-Processor-ExecutionRole"
      AssumeRolePolicyDocument:
        Version:                        "2012-10-17"
        Statement:
          Effect:                       "Allow"
          Principal:
            Service:                    "lambda.amazonaws.com"
          Action:                       "sts:AssumeRole"
      ManagedPolicyArns:
        -                               "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Policies:
        -
          PolicyName:                   "ReadFromSource"
          PolicyDocument:
            Version:                    "2012-10-17"
            Statement:
              Effect:                   "Allow"
              Action:
                -                       "s3:DeleteObject"
                -                       "s3:HeadObject"
                -                       "s3:GetObject"
              Resource:                 [ !Sub "arn:aws:s3:::${BaseBucketName}-uploads/*" ]
        -
          PolicyName:                   "WriteToDestination"
          PolicyDocument:
            Version:                    "2012-10-17"
            Statement:
              Effect:                   "Allow"
              Action:
                -                       "s3:PutObject"
              Resource:                 [ !Sub "arn:aws:s3:::${BaseBucketName}-archive/*" ]


  ProcessorFunction:
    Type:                               "AWS::Lambda::Function"
    Properties: 
      FunctionName:                     !Sub "${AWS::StackName}-Processor"
      Description:                      !Sub "Processes files uploaded to ${BaseBucketName}-uploads and moves them to ${BaseBucketName}-archive"
      Role:                             !GetAtt ProcessorRole.Arn
      Runtime:                          "python3.7"
      Handler:                          "index.lambda_handler"
      Code: 
        ZipFile:                        |
                                        import boto3
                                        import os
                                        
                                        
                                        archive_bucket = os.environ['ARCHIVE_BUCKET']
                                        
                                        s3_client = boto3.client('s3')
                                        
                                        
                                        def lambda_handler(event, context):
                                            for record in event.get('Records', []):
                                                eventName = record['eventName']
                                                bucket = record['s3']['bucket']['name']
                                                key = record['s3']['object']['key']
                                                try:
                                                    process(s3_client, bucket, key)
                                                    archive(s3_client, bucket, key)
                                                except Exception as ex:
                                                    # we'll print the exception and continue with the event
                                                    print(ex)
                                        
                                        
                                        def process(s3_client, bucket, key):
                                            print(f'processing s3://{bucket}/{key}')
                                            meta = s3_client.head_object(Bucket=bucket, Key=key)
                                            print(f"filesize = {meta['ContentLength']}")
                                        
                                        
                                        def archive(s3_client, bucket, key):
                                            print(f'moving s3://{bucket}/{key} to s3://{archive_bucket}/{key}')
                                            s3_client.copy(
                                                CopySource={'Bucket': bucket, 'Key': key },
                                                Bucket=archive_bucket,
                                                Key=key)
                                            s3_client.delete_object(Bucket=bucket, Key=key)
      MemorySize:                       256
      Timeout:                          15
      Environment: 
        Variables:
          ARCHIVE_BUCKET:               !Ref ArchiveBucket


  ProcessorInvocationPermission:
    Type:                               "AWS::Lambda::Permission"
    DependsOn:                          [ ProcessorFunction ]
    Properties:
      Action:                           "lambda:InvokeFunction"
      FunctionName:                     !GetAtt ProcessorFunction.Arn
      Principal:                        "s3.amazonaws.com"
      SourceAccount:                    !Ref AWS::AccountId
      SourceArn:                        !Sub "arn:aws:s3:::${BaseBucketName}-uploads"
