##
## Creates a Lambda that's triggered by an ECS task state change, to record information before
## the task disappears.
##
################################################################################
#
# MIT No Attribution
#
# Copyright Chariot Solutions
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this
# software and associated documentation files (the "Software"), to deal in the Software
# without restriction, including without limitation the rights to use, copy, modify,
# merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
################################################################################

AWSTemplateFormatVersion:               "2010-09-09"
Description:                            "Lambda to capture information about stopped ECS tasks"

Parameters:

  LambdaName:
    Description:                        "Name for the Lambda function and associated resources"
    Type:                               "String"
    Default:                            "ECS_Task_Monitor"

Resources:

  LambdaLogGroup:
    Type:                               "AWS::Logs::LogGroup"
    DeletionPolicy:                     "Delete"
    Properties:
      LogGroupName:                     !Sub "/aws/lambda/${LambdaName}"
      RetentionInDays:                  7


  LambdaRole:
    Type:                               "AWS::IAM::Role"
    Properties:
      Path:                             "/lambda/"
      RoleName:                         !Sub "${LambdaName}-ExecutionRole-${AWS::Region}"
      AssumeRolePolicyDocument:
        Version:                        "2012-10-17"
        Statement:
          Effect:                       "Allow"
          Principal:
            Service:                    "lambda.amazonaws.com"
          Action:                       "sts:AssumeRole"
      ManagedPolicyArns:
        -                               "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"


  LambdaFunction:
    Type:                               "AWS::Lambda::Function"
    Properties:
      FunctionName:                     !Ref LambdaName
      Description:                      "Dumps the invocation event as JSON"
      Role:                             !GetAtt LambdaRole.Arn
      Runtime:                          "python3.9"
      Handler:                          "index.lambda_handler"
      Code:
        ZipFile:                        |
                                        import json

                                        def lambda_handler(event, context):
                                            detail = event["detail"]
                                            
                                            container_summary = []
                                            for container in detail.get("containers", []):
                                                container_summary.append({
                                                    "name":         container.get("name"),
                                                    "image":        container.get("image"),
                                                    "imageDigest":  container.get("imageDigest"),
                                                    "exitCode":     container.get("exitCode"),
                                                })
                                                
                                            service = None
                                            if detail.get("group", "").startswith("service:"):
                                                service =  detail.get("group", "").replace("service:", "")

                                            summary = {
                                                "clusterName":       detail.get("clusterArn", "").split("/")[-1],
                                                "serviceName":       service,
                                                "taskId":            detail.get("taskArn", "").split("/")[-1],
                                                "taskDefinitionArn": detail.get("taskDefinitionArn", ""),
                                                "startedAt":         detail.get("startedAt"),
                                                "stoppedAt":         detail.get("stoppedAt"),
                                                "stopCode":          detail.get("stopCode"),
                                                "stoppedReason":     detail.get("stoppedReason"),
                                                "containers":        container_summary
                                            }
                                            print(json.dumps(summary))
      MemorySize:                       256
      Timeout:                          15


  EventRule:
    Type:                               "AWS::Events::Rule"
    Properties:
      Name:                             "ECS_Task_Completion"
      Description:                      "Fires on the completion of any ECS task"
      State:                            "ENABLED"
      EventPattern:
        source:                         [ "aws.ecs" ]
        detail-type:                    [ "ECS Task State Change" ]
        detail:
          lastStatus:                   [ "STOPPED" ]
      Targets:
        - Id:                           !Ref LambdaFunction
          Arn:                          !GetAtt LambdaFunction.Arn


  InvocationPermission:
    Type:                               "AWS::Lambda::Permission"
    Properties:
      Action:                           "lambda:InvokeFunction"
      FunctionName:                     !GetAtt LambdaFunction.Arn
      Principal:                        "events.amazonaws.com"
      SourceArn:                        !GetAtt EventRule.Arn
