## Creates a pipeline that routes CloudTrail logs onto a Kinesis stream.
##
## To use, you must upload the Lambda deployment bundle and attach the SQS queue to the S3
## bucket that receives CloudTrail files. See the README for detailed instructions.
##
################################################################################
#
# MIT No Attribution
#
# Copyright Chariot Solutions
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this
# software and associated documentation files (the "Software"), to deal in the Software
# without restriction, including without limitation the rights to use, copy, modify,
# merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
################################################################################

AWSTemplateFormatVersion:               "2010-09-09"
Description:                            "Deconstructs CloudTrail log files and writes the events to a Kinesis stream"

Parameters:

  CloudTrailBucket:
    Description:                        "Name of the bucket containing CloudTrail events"
    Type:                               "String"

  CloudTrailBucketPrefix:
    Description:                        "Prefix for CloudTrail events in the source bucket (optional, must have trailing slash if used)"
    Type:                               "String"
    Default:                            ""

  SQSName:
    Description:                        "Name for the SQS queue stream that receives CloudTrail notification events from S3"
    Type:                               "String"
    Default:                            "cloudtrail_notifications"

  RetryCount:
    Description:                        "Number of attempts to process notification before it's moved to DLQ"
    Type:                               "Number"
    Default:                            3

  KinesisStreamName:
    Description:                        "Name for the Kinesis stream that will receive indiviudal events"
    Type:                               "String"
    Default:                            "cloudtrail_events"

  KinesisStreamRetentionHours:
    Description:                        "Hours that messages will be retained in the Kinesis stream"
    Type:                               "Number"
    Default:                            24

  KinesisShardCount:
    Description:                        "Number of the shards on the Kinesis stream; increase for high-volume"
    Type:                               "Number"
    Default:                            1

  LambdaName:
    Description:                        "Name for the Lambda function and associated resources"
    Type:                               "String"
    Default:                            "CloudTrail_Event_Processor"

  LambdaMaximumConcurrency:
    Description:                        "Maximum number of Lambda instances that will be invoked concurrently"
    Type:                               "Number"
    Default:                            16

Resources:

  KinesisStream:
    Type:                               "AWS::Kinesis::Stream"
    Properties: 
      Name:                             !Ref KinesisStreamName
      RetentionPeriodHours:             !Ref KinesisStreamRetentionHours
      StreamModeDetails:
        StreamMode:                     "PROVISIONED"
      ShardCount:                       !Ref KinesisShardCount


  NotificationQueue:
    Type:                               "AWS::SQS::Queue"
    Properties: 
      QueueName:                        !Ref SQSName
      MessageRetentionPeriod:           1209600 # two weeks (maximum allowed value)
      VisibilityTimeout:                360     # 6x 30 second timeout for Lambda function
      RedrivePolicy: 
        deadLetterTargetArn:            !GetAtt NotificationDLQ.Arn
        maxReceiveCount:                !Ref RetryCount


  NotificationQueuePolicy: 
    Type:                               "AWS::SQS::QueuePolicy"
    Properties: 
      Queues:                           [ !Ref NotificationQueue ]
      PolicyDocument: 
        Statement: 
          - Effect:                     "Allow"
            Action:                     "sqs:SendMessage" 
            Resource:                   !GetAtt NotificationQueue.Arn
            Principal:  
              Service:                  [ "s3.amazonaws.com" ]
            Condition:
              StringEquals:             { "aws:SourceAccount": !Ref AWS::AccountId }


  NotificationDLQ:
    Type:                               "AWS::SQS::Queue"
    Properties: 
      QueueName:                        !Sub "${SQSName}-dlq"
      MessageRetentionPeriod:           604800  # 7 days


  LambdaLogGroup:
    Type:                               "AWS::Logs::LogGroup"
    DeletionPolicy:                     "Delete"
    Properties:
      LogGroupName:                     !Sub "/aws/lambda/${LambdaName}"
      RetentionInDays:                  7


  LambdaRole:
    Type:                               "AWS::IAM::Role"
    Properties:
      Path:                             "/lambda/"
      RoleName:                         !Sub "${LambdaName}-ExecutionRole-${AWS::Region}"
      AssumeRolePolicyDocument:
        Version:                        "2012-10-17"
        Statement:
          Effect:                       "Allow"
          Principal:
            Service:                    "lambda.amazonaws.com"
          Action:                       "sts:AssumeRole"
      ManagedPolicyArns:
        -                               "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Policies:
        - PolicyName:                   "ReceiveFromSQS"
          PolicyDocument:
            Version:                    "2012-10-17"
            Statement:
                Effect:                 "Allow"
                Action:                   
                  -                     "sqs:ReceiveMessage"
                  -                     "sqs:DeleteMessage"
                  -                     "sqs:GetQueueAttributes"
                Resource:                 
                  -                     !GetAtt NotificationQueue.Arn
        - PolicyName:                   "ReadFromS3"
          PolicyDocument:
            Version:                    "2012-10-17"
            Statement:
                Effect:                 "Allow"
                Action:                   
                  -                     "s3:GetObject"
                Resource:                 
                  -                     !Sub "arn:aws:s3:::${CloudTrailBucket}/${CloudTrailBucketPrefix}*"
        - PolicyName:                   "WriteToKinesis"
          PolicyDocument:
            Version:                    "2012-10-17"
            Statement:
                Effect:                 "Allow"
                Action:                   
                  -                     "kinesis:PutRecords"
                Resource:                 
                  -                     !GetAtt KinesisStream.Arn


  LambdaFunction:
    Type:                               "AWS::Lambda::Function"
    Properties:
      FunctionName:                     !Ref LambdaName
      Description:                      "Writes CloudTrail events to a Kinesis data stream"
      Role:                             !GetAtt LambdaRole.Arn
      Runtime:                          "python3.12"
      Handler:                          "index.lambda_handler"
      Code:
        ZipFile:                        |
                                        def lambda_handler(event, context):
                                            raise Exception("you must separately deploy Lambda code")
      MemorySize:                       2048
      Timeout:                          30
      Environment:
        Variables:
          KINESIS_STREAM:               !Ref KinesisStream


  Trigger:
    Type:                               "AWS::Lambda::EventSourceMapping"
    Properties:
      BatchSize:                        1
      EventSourceArn:                   !GetAtt NotificationQueue.Arn
      FunctionName:                     !GetAtt LambdaFunction.Arn
      ScalingConfig: 
        MaximumConcurrency:             !Ref LambdaMaximumConcurrency


Outputs:

  NotificationQueueUrl:
    Description:                        "URL of the queue that triggers Lambda"
    Value:                              !Ref NotificationQueue

